Make zenoss initscript LSB compliant and clusterable.
Fixes #7252. Reviewed by kkearney.

git-svn-id: http://dev.zenoss.com/svnint/trunk/core@35755 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenctl b/bin/zenctl
--- a/bin/zenctl
+++ b/bin/zenctl
@@ -226,6 +226,24 @@ upgrade_post() {
 # to the zenoss database through the web UI
 #
 
+# LSB exit code reference.
+#   0       program is running or service is OK
+#   1       program is dead and /var/run pid file exists
+#   2       program is dead and /var/lock lock file exists
+#   3       program is not running
+#   4       program or service status is unknown
+#   5-99    reserved for future LSB use
+#   100-149 reserved for distribution use
+#   150-199 reserved for application use
+#   200-254 reserved
+
+# When run in an HA configuration with $ZENHOME on shared storage the real
+# Zenoss startup script may not exist.
+if [ ! -f "${ZENHOME}/bin/zenoss" ]; then
+    echo "Startup script not found at ${ZENHOME}/bin/zenoss."
+    exit 3
+fi
+
 # run the firstboot if this is the first time zenoss was started
 if [ "$1" = start -a -f ${FRESH_INSTALL} ]; then
     fresh_install_pre
@@ -240,7 +258,7 @@ fi
 
 # delegate to the main zenoss script for control functions
 su - ${RUNUSER} sh -c "${ZENHOME}/bin/zenoss $@"
-
+EXITCODE=$?
 
 # run the post-script for firstboot and remove the firstboot flag
 if [ "$1" = start -a -f ${FRESH_INSTALL} ]; then
@@ -262,3 +280,5 @@ if [ ! -z "$tee_pid" ] ; then
     # Zombies are bad. Bad zombies
     wait $tee_pid
 fi
+
+exit $EXITCODE
diff --git a/bin/zenoss b/bin/zenoss
--- a/bin/zenoss
+++ b/bin/zenoss
@@ -98,26 +98,56 @@ reverse() {
 FUNC=$CMD
 
 issue() {
-    HUBCODE=4
+    # To properly conform to LSB standards and be used under Linux-HA or RHCS
+    # we need to exit with a proper non-zero code when there is a problem with
+    # the service. We'll take the naive approach of responding with the highest
+    # and most likely worse condition of any of the configured daemons.
+    HIGHESTCODE=0
     for cmd in $CMDS
     do
         echo -n "Daemon: $cmd "
-        $ZENHOME/bin/$cmd "$FUNC"
-        CODE=$?
-        if [ $cmd == "zenhub" ]; then
-            HUBCODE=$CODE
+        
+        # Special status handling for zeoctl and zopectl because the stock
+        # scripts exit with a code of 0 no matter what state they're in.
+        if [ $FUNC == "status" -a \( $cmd == "zeoctl" -o $cmd == "zopectl" \) ]
+        then
+            PIDFILE="${ZENHOME}/var/Z2.pid"
+            [ $cmd == 'zeoctl' ] && PIDFILE="${ZENHOME}/var/ZEO.pid"
+
+            if running; then
+                echo program running\; pid=$PID
+                CODE=0
+            else
+                echo not running
+                if [ -f $PIDFILE ]; then
+                    rm -f $PIDFILE
+                    CODE=1
+                else
+                    CODE=3
+                fi
+            fi
+        else
+            $ZENHOME/bin/$cmd "$FUNC"
+            CODE=$?
+        fi
+        if [ $CODE -gt $HIGHESTCODE ]; then
+            HIGHESTCODE=$CODE
         fi
     done
-    return $HUBCODE
+    return $HIGHESTCODE
 }
+
+EXITCODE=4
 
 case "$FUNC" in
   start)
         issue
+        EXITCODE=$?
         ;;
   stop)
         CMDS=`reverse $CMDS`
         issue
+        EXITCODE=$?
 	rm -f $ZENHOME/var/.*watchdog-*
         ;;
   restart)
@@ -127,18 +157,21 @@ case "$FUNC" in
         CMDS=`reverse $CMDS`
 	FUNC=start
         issue
+        EXITCODE=$?
         ;;
   status)
         issue
+        EXITCODE=$?
         ;;
   list)
 	for i in $CMDS
 	do
 	    echo $i
+	    EXITCODE=0
 	done
 	;;
   *)
         echo $"Usage: $0 {start|stop|restart|status|list}"
         exit 1
 esac
-exit $?
+exit $EXITCODE
