fixes ZEN-1310: gracefully catch an edgecase if ZenDS is partially installed/uninstalled; reviewed by jwhitworth
git-svn-id: http://dev.zenoss.com/svnint/trunk/core@56867 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenctl b/bin/zenctl
--- a/bin/zenctl
+++ b/bin/zenctl
@@ -47,8 +47,8 @@ export ZENHOME="**ZENHOME**"
 export INSTALL_LOG="$ZENHOME/log/install.log"
 . $ZENHOME/bin/zenoss_startup_config  
 if [ "$?" -ne 0 ]; then
-   echo "In $BN, error loading zenoss_startup_config."
-   exit 1 
+    echo "${BN}: Error loading zenoss_startup_config."
+    exit 3 
 fi
 
 # NB: This crude hack is to add output while preserving return codes
@@ -65,12 +65,23 @@ export UPGRADED=${ZENHOME}/.upgraded
 
 ZENDSPROFILE=/etc/profile.d/zends_env.sh
 if [ -f "${ZENDSPROFILE}" ];then
-        source ${ZENDSPROFILE}
-        if [ "${USE_ZENDS}" = "1" ];then
-                export PATH=${ZENDSHOME}/bin:${PATH}
-                export LD_LIBRARY_PATH=${ZENDSHOME}/lib:${LD_LIBRARY_PATH}
-                source ${ZENDSHOME}/scripts/aliases
+    source ${ZENDSPROFILE}
+    if [ "${USE_ZENDS}" = "1" ];then
+        export PATH=${ZENDSHOME}/bin:${PATH}
+        export LD_LIBRARY_PATH=${ZENDSHOME}/lib:${LD_LIBRARY_PATH}
+        if [ -f "${ZENDSHOME}/scripts/aliases" ];then
+            source ${ZENDSHOME}/scripts/aliases
+        else
+            echo "${BN}: Error:  Missing ${ZENDSHOME}/scripts/aliases."
+            echo
+            echo "You appear to have an incomplete installation of the Zenoss Datastore, ZenDS."
+            echo "ZenDS is a requirement for Zenoss masters and remote hubs."
+            echo "ZenDS is a not a requirement for remote collectors."
+            echo
+            echo "Please cleanup or reinstall ZenDS as appropriate."
+            exit 3
         fi
+    fi
 fi
 
 # changes the owners and permissions for the zenoss files
