fix startup errors in RPM, check for gcc <= 4.5, use global.conf to trickle down settings; reviewed by pwarren.
git-svn-id: http://dev.zenoss.com/svnint/trunk/core@49244 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenctl b/bin/zenctl
--- a/bin/zenctl
+++ b/bin/zenctl
@@ -38,12 +38,18 @@
 # zenoss_upgrade_pos
 #
 
+BN=$0
+
 # environment variables
 # NB: Please keep the ZENHOME='**ZENHOME**' idiom alive in the src.  Tags
 #     of this nature are sed substituted at build time based upon the package type.
 export ZENHOME="**ZENHOME**"
 export INSTALL_LOG="$ZENHOME/log/install.log"
-. $ZENHOME/bin/zenoss_startup_config
+. $ZENHOME/bin/zenoss_startup_config  
+if [ "$?" -ne 0 ]; then
+   echo "In $BN, error loading zenoss_startup_config."
+   exit 1 
+fi
 
 # NB: This crude hack is to add output while preserving return codes
 # Uses the concepts from http://www.travishartwell.net/blog/2006/08/19_2220
