Fixes #28542: Be smarter about the way we restart; check that we're actually dead before starting. Warn the user if unable to stop. Reviewed by Philip.
git-svn-id: http://dev.zenoss.com/svnint/trunk/core@44540 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenfunctions b/bin/zenfunctions
--- a/bin/zenfunctions
+++ b/bin/zenfunctions
@@ -133,13 +133,28 @@ stop() {
 
 restart() {
     PIDFILE=`pidFile $CFGFILE`
+    PID=`cat $PIDFILE 2>/dev/null`
+    SUCCEEDED=
     stop
     for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
     do
-       sleep 0.24 2>/dev/null || sleep 1
-       test -f $PIDFILE || break
+       sleep 0.75 2>/dev/null || sleep 1
+       if [ ! -f $PIDFILE ]; then
+           SUCCEEDED=1
+           break
+       fi
     done
-    start "$@"
+    # Double-check ps output in case the pid file is stale
+    if [ -z "$SUCCEEDED" ]; then
+        ps -p $PID >/dev/null 2>&1 || SUCCEEDED=1
+    fi
+    # If we still haven't stopped, warn and fail, otherwise start
+    if [ -z "$SUCCEEDED" ]; then
+        echo "Unable to shut down process $PID. You might need to kill it manually."
+        exit 1
+    else
+        start "$@"
+    fi
 }
 
 status() {
