reviewed by smousa fixes ZEN-1580 when a value was missing it was being set to the error message
git-svn-id: http://dev.zenoss.com/svnint/trunk/core@58919 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenoss_startup_config b/bin/zenoss_startup_config
--- a/bin/zenoss_startup_config
+++ b/bin/zenoss_startup_config
@@ -21,7 +21,7 @@ function get_var {
 
     OUTPUT=`su $RUNUSER -l -c "$ZENHOME/bin/zenglobalconf -p $VAR_NAME"`
     if [ $? != 0 ]; then
-       echo "$VAR_NAME could not be set. Check $ZENHOME/etc/global.conf for value."
+       echo "$VAR_NAME could not be set. Check $ZENHOME/etc/global.conf for value." >&2
        exit 1
     fi
     echo $OUTPUT
@@ -78,5 +78,3 @@ export RABBITMQ_PORT="`get_var amqpport`"
 export RABBITMQ_VHOST="`get_var amqpvhost`"
 export RABBITMQ_USER="`get_var amqpuser`"
 export RABBITMQ_PASS="`get_var amqppassword`"
-
-
