ZEN-6523 Ensure rabbitmq connectivity before proceeding with zenoss migration   - Added packages required for centos dev enviroment in INSTALL.txt   - Modified qverify.py to allow version and settings check bypass while still testing connectivity   - Added install functions to test for local rabbitmq configuration   - Modifed start rabbit mq function to fail when service start fails   - Updated zenoss_upgrade_pre to always test for connectivity and start/configure rabbitmq when rabbit is local
reviewed by John Causey



git-svn-id: http://dev.zenoss.com/svnint/trunk/core@72844 f5df01ce-0320-0410-9ed9-ddcd13c732cc

diff --git a/bin/zenoss_upgrade_pre b/bin/zenoss_upgrade_pre
--- a/bin/zenoss_upgrade_pre
+++ b/bin/zenoss_upgrade_pre
@@ -102,10 +102,19 @@ sed -i -e 's/[ \t]*configpath .*//' $ZENHOME/etc/zenstatus.conf
 if [ "${ZODB_HOST}" = "localhost" ];then
     check_mysql
 fi
-start_rabbitmq
 
-# Update AMQP configuration files
-configure_amqp
+# start/configure amqp/rabbitmq if configured to run locally
+if is_amqp_local ; then
+    # start it
+    start_rabbitmq
+
+    # Update AMQP configuration files
+    configure_amqp
+fi
+
+if ! confirm_amqp_connectivity ; then
+    fail "Failed connecting to rabbitmq"
+fi
 
 # patch any ZenPack code that isn't compatible with this version of core
 . ${ZENHOME}/bin/zenoss_upgrade_patch_zenpacks.sh
